// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using St_Patrick_and_St_Joseph_Choir_API.Data;

#nullable disable

namespace St_Patrick_and_St_Joseph_Choir_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231005072322_CreateTables")]
    partial class CreateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("St_Patrick_and_St_Joseph_Choir_API.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MemberId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            Birthday = new DateTime(2000, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ljane.dio@gmail.com",
                            Name = "Lucy D",
                            Status = 1
                        },
                        new
                        {
                            MemberId = 2,
                            Birthday = new DateTime(2000, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "thomasjbpark324@gmail.com",
                            Name = "Thomas",
                            Status = 1
                        },
                        new
                        {
                            MemberId = 3,
                            Birthday = new DateTime(2000, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "audeehalim@gmail.com",
                            Name = "Audee",
                            Status = 1
                        },
                        new
                        {
                            MemberId = 4,
                            Birthday = new DateTime(2000, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jericjaymallari@gmail.com",
                            Name = "Jeric",
                            Status = 1
                        },
                        new
                        {
                            MemberId = 5,
                            Birthday = new DateTime(2000, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "adavalsantos@gmail.com",
                            Name = "Ally",
                            Status = 1
                        },
                        new
                        {
                            MemberId = 6,
                            Birthday = new DateTime(2000, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            Name = "Delysse",
                            Status = 3
                        },
                        new
                        {
                            MemberId = 7,
                            Birthday = new DateTime(2000, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sonadavsan@gmail.com",
                            Name = "Sona",
                            Status = 1
                        },
                        new
                        {
                            MemberId = 8,
                            Birthday = new DateTime(2000, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sabinalama@gmail.com",
                            Name = "Sabina",
                            Status = 1
                        },
                        new
                        {
                            MemberId = 9,
                            Birthday = new DateTime(2000, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mr.khoa1412@gmail.com",
                            Name = "Kelvin",
                            Status = 1
                        },
                        new
                        {
                            MemberId = 10,
                            Birthday = new DateTime(2000, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ninzrevalde@gmail.com",
                            Name = "Niña",
                            Status = 1
                        },
                        new
                        {
                            MemberId = 11,
                            Birthday = new DateTime(2000, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jfbenavid@gmail.com",
                            Name = "Fabian",
                            Status = 1
                        },
                        new
                        {
                            MemberId = 12,
                            Birthday = new DateTime(2000, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "acanjohnpaul07@gmail.com",
                            Name = "Paul",
                            Status = 1
                        },
                        new
                        {
                            MemberId = 13,
                            Birthday = new DateTime(2000, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nikkoverdionisio@yahoo.co.nz",
                            Name = "Nikko",
                            Status = 1
                        },
                        new
                        {
                            MemberId = 14,
                            Birthday = new DateTime(2000, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maye.benitezparra@gmail.com",
                            Name = "Mayerly",
                            Status = 1
                        },
                        new
                        {
                            MemberId = 15,
                            Birthday = new DateTime(2000, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "agonhd@gmail.com",
                            Name = "Harsen",
                            Status = 1
                        },
                        new
                        {
                            MemberId = 16,
                            Birthday = new DateTime(2000, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lucia.dk83@gmail.com",
                            Name = "Lucia K",
                            Status = 1
                        },
                        new
                        {
                            MemberId = 17,
                            Birthday = new DateTime(2000, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "willsenwijaya@gmail.com",
                            Name = "Willsen",
                            Status = 1
                        },
                        new
                        {
                            MemberId = 18,
                            Birthday = new DateTime(2000, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omallnico@myvuw.ac.nz",
                            Name = "Nicola",
                            Status = 1
                        },
                        new
                        {
                            MemberId = 19,
                            Email = "verondionisio@yahoo.co.nz",
                            Name = "Veronica",
                            Status = 2
                        });
                });

            modelBuilder.Entity("St_Patrick_and_St_Joseph_Choir_API.Models.Music", b =>
                {
                    b.Property<int>("MusicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusicId"));

                    b.Property<byte[]>("MusicSheet")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Soloist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Song")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YoutubeUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusicId");

                    b.ToTable("Musics");

                    b.HasData(
                        new
                        {
                            MusicId = 1,
                            Soloist = "",
                            Song = "Processional/Entrance",
                            Title = "",
                            YoutubeUrl = ""
                        },
                        new
                        {
                            MusicId = 2,
                            Soloist = "",
                            Song = "Gloria",
                            Title = "",
                            YoutubeUrl = ""
                        },
                        new
                        {
                            MusicId = 3,
                            Soloist = "",
                            Song = "Psalm",
                            Title = "",
                            YoutubeUrl = ""
                        },
                        new
                        {
                            MusicId = 4,
                            Soloist = "",
                            Song = "Gospel Acclamation",
                            Title = "",
                            YoutubeUrl = ""
                        },
                        new
                        {
                            MusicId = 5,
                            Soloist = "",
                            Song = "Offertory",
                            Title = "",
                            YoutubeUrl = ""
                        },
                        new
                        {
                            MusicId = 6,
                            Soloist = "",
                            Song = "Holy",
                            Title = "",
                            YoutubeUrl = ""
                        },
                        new
                        {
                            MusicId = 7,
                            Soloist = "",
                            Song = "Memorial Acclamation",
                            Title = "",
                            YoutubeUrl = ""
                        },
                        new
                        {
                            MusicId = 8,
                            Soloist = "",
                            Song = "Lamb of God",
                            Title = "",
                            YoutubeUrl = ""
                        },
                        new
                        {
                            MusicId = 9,
                            Soloist = "",
                            Song = "Communion",
                            Title = "",
                            YoutubeUrl = ""
                        },
                        new
                        {
                            MusicId = 10,
                            Soloist = "",
                            Song = "Recessional",
                            Title = "",
                            YoutubeUrl = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
